#' Function calculating (asymptotic) confidence intervals
#'
#' This functions calculates asymptotic (1-alpha) confidence intervals for the coefficients in different regression settings.
#' The chosen loss function determines the regression setting and for estimating the asymptotic covariance matrix
#' the results of previous calls of \code{\link{m}} / \code{\link{m_gam}} are used.
#' For \code{loss="mean"} it is also possible to calculate the exact (1-alpha) confidence interval under the normal distribution assumption.
#' Those confidence intervals need to be carefully interpreted since the asymptotic justifications demand for different assumptions
#' which do not have to be fullfilled.
#'
#' @param x design matrix
#' @param obj object generated by a previous call of \code{\link{m}} or \code{\link{m_gam}}
#' @param loss type of loss function: \code{"nils"} = approach of Oelker et al. (2015),
#' \code{"kemp"} = approach of Kemp et al. (2012), \code{"mean"} = mean regression, \code{"med"} = approximation of median
#' regression
#' @param alpha confidence level
#' @param exact logical; for \code{loss="mean"}: \code{exact="TRUE"} can be chosen to calculate the exact
#' confidence interval under the normal distribution assumption
#' @param kernel for \code{loss="med"}: kernel for estimating the asymptotic covariance matrix (\code{gaussian} or \code{uniform})
#' @return \describe{
#' \item{\code{ci}}{matrix containing the confidence intervals for the different coefficients as rows}
#' \item{\code{length}}{vector containing the length of the confidence intervals}
#' }
#' @export

confidence_interval <- function(
  x,
  obj,
  loss,
  alpha = 0.05,
  exact = FALSE,
  kernel = "gaussian"
){
  quantile <- qnorm(1 - alpha/2)

  if (loss == "nils" || loss =="kemp") {
    Omegahat <- obj$Omegahat
  } else if (loss == "mean" && exact == FALSE) {
    Chatinv <- solve(t(x) %*% x)
    Bhat <- t(x) %*% diag(as.vector(obj$residuals^2)) %*% x
    Omegahat <- Chatinv %*% Bhat %*% Chatinv
  } else if (loss == "mean" && exact == TRUE) {
    df <- nrow(x) - length(obj$coefficients)
    sigma2 <- sum(obj$residuals^2)/df
    Omegahat <- sigma2 * solve(t(x) %*% x)
    quantile <- qt(1 - alpha/2, df)
  } else if (loss == "med") {
    n <- nrow(x)
    h <- n^(-1/3) * quantile^(2/3) * (1.5 * (dnorm(qnorm(0.5))^2 / (2*qnorm(0.5)^2+1)))^(1/3)
    # kappa chosen as in quantreg::summary.rq
    kappa <- min(sqrt(var(obj$residuals)), (quantile(obj$residuals, 0.75) - quantile(obj$residuals, 0.25)) / 1.34)
    c <- kappa * (qnorm(0.5 + h) - qnorm(0.5 - h))
    if (kernel == "uniform") {
      # kernel choice of Powell (1991)
      D <- (2*c)^(-1) * diag(as.numeric(abs(obj$residuals) < rep(c, length(obj$residuals))))
    } else {
      # kernel choice of Koenker in quantreg::summary.rq
      D <- diag(as.vector(dnorm(obj$residuals/c)/c))
    }
    Chatinv <- solve(t(x) %*% D %*% x)
    Bhat <- crossprod(x)
    Omegahat <- 0.25 * Chatinv %*% Bhat %*% Chatinv
  } else {
    stop("You need to choose one of the following losses: nils, kemp, mean, med.
         You can only set exact == TRUE for the loss mean.
         The kernel choice is only relevant for the loss med.")
  }

  c <- quantile * sqrt(diag(Omegahat))
  ci <- cbind(obj$coefficients - c, obj$coefficients + c)
  rownames(ci) <- colnames(x)
  length <- 2*c
  return(list(ci = ci, length = length))
}
